[package]
name = "jsonc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast-float = "0.2.0"
jsonb = { git = "https://github.com/CookiePieWw/jsonb.git", branch = "main" }
